export const LOG_OUT = "LOG_OUT";
export const LOG_OUT_FAILED = "LOG_OUT_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SUBSCRIPTION_REQUEST = "SUBSCRIPTION_REQUEST";
export const SUBSCRIPTION_FAILED = "SUBSCRIPTION_FAILED";
export const SUBSCRIPTION_SUCCESS = "SUBSCRIPTION_SUCCESS";

export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";

export const DELETE_SESSION_REQUEST = "DELETE_SESSION_REQUEST";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
